### ISSUE TITLE
VPC Configuration

### ISSUE THREAD

**Issue by dested** [serverless/containers#12]
I am trying to combine this with CDK in a nice way, and it'd be wonderful if I could create the VPC in cdk and set simply set it like:

```
containers:
  service:
    compute:
      type: awsFargateEcs
      awsFargateEcs:
        vpc: vpc-12345
```

Any advice is helpful!
