### ISSUE TITLE
Config: Build with docker

### ISSUE THREAD

**Issue by trykovyura** [serverless/containers#6]
Hi, thanks for great tool! Trying to customise build configuration, but found some issues and i need some help. 

# Use cases
- Build monorepo with nextjs 
- Respository structure is classic for [turborepo](https://turbo.build/repo/docs/crafting-your-repository/structuring-a-repository)
- Have several apps to build with docker and deploy with [serverless container](https://www.serverless.com/containers/docs/getting-started)

<img width="802" alt="Image" src="https://github.com/user-attachments/assets/810c8441-8a3e-401a-9d1f-80486cae3fad" />

# Build config
```
name: example

deployment:
  type: awsApi@1.0

containers:
  example-docs:
    src: ./apps/example-docs
    routing:
      domain: dev-docs.example.com
      pathPattern: /*
      pathHealthCheck: /api/health
    environment:
      HELLO: world
    compute:
      type: awsFargateEcs
  example-web:
    src: ./apps/example-web
    compute:
      type: awsFargateEcs
      awsFargateEcs:
        cpu: 256
        memory: 512
    build:
      args: # Optional: Arguments to pass to the build, as a map of key-value pairs. This is useful for passing in build arguments to the Dockerfile, like ssh keys to fetch private dependencies, etc.
        key: value # Example: ARG key=value
      dockerFileString: ./apps/example-web/Dockerfile
    routing:
      domain: dev-web.example.com
      pathPattern: /*
      pathHealthCheck: /api/health
    environment:
      HELLO: world
```

# Build error
When i try to deploy this config - it errors with on `serverless deploy`
 - Unrecognized key(s): build
```
{
    "source": "sfcore.analysis.generated.v1",
    "event": {
      "actionSucceeded": false,
      "operatingSystem": "linux",
      "architecture": "x64",
      "cicd": true,
      ...
      "isCompose": false,
      "projectType": "containers",
      "cliOptions": [
        "stage",
        "debug"
      ],
      "source": "serverless@4.6.2",
      "actionName": "deploy",
      "configurationFileName": "serverless.containers.yml",
      "resolvers": [],
      "error": {
        "name": "Error",
        "message": "Invalid configuration:\n\n  - Unrecognized key(s): build\n\n",
        "code": "INVALID_CONFIGURATION"
      }
    }
  }
```

# Build error analysis
- [Container framework configuration](https://www.serverless.com/containers/docs/configuration) is correct ✅ 
- Example
```
containers:
  my-container:
    src: ./path/to/container # Required: Path to the container source code.
    compute: # Required: Compute configuration.
    build: # Optional: Build configuration.
    environment: # Optional: Environment variables to pass to the container.
    routing: # Required: Routing configuration.
    dev: # Optional: Development mode configuration
```
- Actual 
```
example-web:
    src: ./apps/example-web
    compute:
    build:
      args: # Optional: Arguments to pass to the build, as a map of key-value pairs. This is useful for passing in build arguments to the Dockerfile, like ssh keys to fetch private dependencies, etc.
        key: value # Example: ARG key=value
      dockerFileString: ./apps/example-web/Dockerfile
```
- Could not find source code to check - is it opensoured? 
- Main hypothesis - looks like a bug 🐛 

## Docker examples? 
- Could not find any example in repository https://github.com/serverless/containers
- Could not find any example in https://www.serverless.com/containers/docs/configuration 

## More bugs?
- hypothesis that `dockerFileString` -> supposed to be `dockerFile` as is see in serverless configuration 

## Proposual for configuration update
- Based on [docker-compose configuration](https://docs.docker.com/reference/compose-file/build/) vs [serverless-container configuration](https://www.serverless.com/containers/docs/configuration):
  - Serverless:  `src: ./path/to/container` - Path to the container source code and mainly build context for Dockerfile
  - Docker compose: `context: .` - build context for docker file

### Add build context to separate src and context
- Why? Monorepo use cases - all build made from root build context. 
  - Why? Prepare repo - with prune command  https://turbo.build/repo/docs/reference/prune
    - Why? Nextjs standalone build for docker - https://nextjs.org/docs/pages/building-your-application/deploying
Would be great to add build context for Dockerfile.
Example: 
```
build:
  args: # Optional: Arguments to pass to the build, as a map of key-value pairs. This is useful for passing in build arguments to the Dockerfile, like ssh keys to fetch private dependencies, etc.
    key: value # Example: ARG key=value
  dockerFileString: # Optional: Dockerfile as a string to use for the container (not recommended, prefer
  context: # Optional: Build context for docker file```

**Comment by austencollins** [comment]
@trykovyura This is our fault for pushing out docs before the new release that features the "build" property. We are shipping this release on Monday and this feature will be available then.

**Comment by trykovyura** [comment]
@austencollins no problem. If you know estimated version, it would be great to track release. 
Lastest release 5 days ago https://github.com/serverless/serverless/releases/tag/v4.6.3 - suppose waiting for 4.6.4 or 4.7.0?

**Comment by Mmarzex** [comment]
@trykovyura 4.6.3 was releases yesterday and adds the build args support.

**Comment by trykovyura** [comment]
Nice. 
Tried 4.6.3 

-  Fixed "message": `"Invalid configuration:\n\n  - Unrecognized key(s): build\n\n"` ✅ 
- But error on parsing path `ERROR: failed to solve: dockerfile parse error on line 1: unknown instruction: ./apps/example-app/Dockerfile` ❌ 

## Config 
```
example-app:
    src: .
    compute:
      type: awsFargateEcs
      awsFargateEcs:
        cpu: 256
        memory: 512
    build:
      dockerFileString: ./apps/example-app/Dockerfile
    routing:
      domain: dev-app.surprisesantas.com
      pathPattern: /*
      pathHealthCheck: /api/health
```
